version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
