spring.application.name=todoapp

# Server Port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/todoapp}

# JWT Configuration
app.jwt.secret=${JWT_SECRET:thisisasecretkeywhichshouldbeatleast256bitslongsothatitworks}
app.jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}
