spring.application.name=todoapp
server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/todoapp}
app.jwt.secret=thisisasecretkeywhichshouldbeatleast256bitslongsothatitworks
app.jwt.expirationMs=86400000
