spring.application.name=todoapp
server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://osadanirmal9_db_user:XxG4bZLnG8pqYSFX@cluster0.2srtckv.mongodb.net}
app.jwt.secret=thisisasecretkeywhichshouldbeatleast256bitslongsothatitworks
app.jwt.expirationMs=86400000
